In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
# ブールインデックスによる条件付き操作
# 条件を満たす要素を取得
arr[arr>3]

array([4, 5, 6])

In [5]:
arr > 3

array([False, False, False,  True,  True,  True])