In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [3]:
np.random.randint(0,100,size=10)

array([32, 60, 52, 43, 82, 37, 50, 52, 70, 28])

In [4]:
# 正規分布に従うランダム配列を作成
np.random.randn(3,3)

array([[-0.69753822, -0.23748104, -0.581999  ],
       [ 0.11617379,  0.5386268 , -0.30995001],
       [-1.51228308,  0.88977838,  0.36750962]])