In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [4]:
arr1 + arr2

array([5, 7, 9])

In [5]:
arr1 * arr2

array([ 4, 10, 18])