In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [11]:
# 配列の結合
arr3 = np.concatenate((arr1, arr2))
arr3

array([1, 2, 3, 4, 5, 6])

In [13]:
arr4,arr5,arr6 = np.split(arr, 3)
arr4

array([1, 2])

In [15]:
arr5

array([3, 4])

In [14]:
arr6

array([5, 6])