In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [3]:
np.mean(arr)

np.float64(3.5)

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.mean(arr2)

np.float64(3.5)

In [7]:
# axis=0は列方向、axis=1は行方向
np.mean(arr2,axis=0)

array([2.5, 3.5, 4.5])